### ISSUE TITLE
Issue with generating chunks and creating a new world.

### ISSUE THREAD

**Issue by SethZurborg** [Gamealition/WorldBorder-Forge#13]
From my observations, if you want a new world while another world is being generated, the world that is being generated will begin generating chunks belonging to the newly created world. 
Mod Pack being used FTB Infinity Evolved 2.2.2

Steps to Reproduce (Using RFTools as the dim creator)
1. Make a world, and allows a specific set of biomes.
2. Start filling the world using WorldBorder-Forge
3. Make new world that allow a single biome.
4. When the generation of the initial world is done, it will contain [misgenerated chunks](https://drive.google.com/file/d/0B0c5T4bkwhIiNjVhU1N5Mk9wd2M/view?usp=sharing)
Posted here and on the [RFTools](https://github.com/McJty/RFTools/issues/424) issue tracker.

**Comment by RoyCurtis** [comment]
Interesting. It's possibly a race condition; I will need to double-check if WorldBorder-Forge generates chunks on the main thread. Will also need to check how WB interfaces with the world's generator.

I will be unable to attend to this bug for approx. 2 weeks because of real life obligations. In the meantime, I would like more information:

* Was this discovered in single player or multiplayer?
* If multiplayer, is it on a KCauldron server?

Thank you for reporting this on the RFTools tracker also. I would be curious to know your answer to McJty's question about other dim providers.

**Comment by SethZurborg** [comment]
Alright. I have been looking through it to see if anything jumps out at me, i have yet to see anything in your code. I'll continue to keep looking, on the chance i find something, do you accept pull requests?

* This is on a FTB Infinity Evolved Server, which is running fastcraft(forgot to mention that before)
* No, beyond the mods included in that pack dynmap and this mod are the only changes.

**Comment by SethZurborg** [comment]
We have had this occur on a world that did not utilize WB in any fashion, i am going to mark this as closed and hope @McJty finds and resolves the bug.

**Comment by RoyCurtis** [comment]
Thank you for the update
